_commit: v2.1.1
_src_path: gh:mopidy/mopidy-ext-template
author_email: stein.magnus@jodal.no
author_full_name: Stein Magnus Jodal
dist_name: mopidy-mpd
ext_name: mpd
github_username: mopidy
short_description: Mopidy extension for controlling Mopidy from MPD clients
